services:
  waf:
    build: .
    container_name: waf
    ports:
      - "8080:8080"
    entrypoint: ["nginx", "-g", "daemon off;"]
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/nginx-proxy.conf:/etc/nginx/conf.d/default.conf:ro
      - ./modsecurity/main.conf:/etc/modsecurity.d/main.conf:ro
    depends_on:
      - app

  app:
    image: bkimminich/juice-shop
    container_name: app